import Head from 'next/head'
import Image from 'next/image'
import { Button } from '@nextjs-lerna/shared'
import { useForm } from 'react-hook-form'

import styles from '../styles/Home.module.css'
import { useContext } from 'react'
import { AuthContext } from './contexts/AuthContext'

export default function Home() {
  const { register, handleSubmit } = useForm()

  const { signIn } = useContext(AuthContext)

  async function handleSignIn(data) {
    await signIn(data)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button />

      <main className={styles.main}>
        <form onSubmit={() => handleSubmit(handleSignIn)}>
          <input
            {...register('email')}
            type="email"
            name="email"
            required
          />
          <input
            {...register('password')}
            type="password"
            name="password"
            required
          />
          <button type="submit">Login</button>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
